### PR TITLE
Fixed unresolved import statement.

### PR DESCRIPTION
**Pull request by KNSHQ**

### CODE REVIEW

**Comment by UmayirFeroze** [comment]
Code has conflicts, resolve before pull request.

**Comment by KNSHQ** [comment]
> Code has conflicts, resolve before pull request.

This has been fixed.

**Comment by KNSHQ** [comment]
[NPM Spec issue](https://trello.com/c/WTwVjiVy/374-npm-spec-issue)

**Comment by KNSHQ** [comment]
[Migration from vanilla css and bootstrap to tailwindCSS.](https://trello.com/c/00c84poB/348-migration-from-vanilla-css-and-bootstrap-to-tailwindcss)

**Comment by KNSHQ** [comment]
[Various Build Stage Bug](https://trello.com/c/rTkd81Zm/375-various-build-stage-bug)

**Review by UmayirFeroze — APPROVED** [review]
Code Reviewed and Merged

**Pull request merged**
