### PR TITLE
User account portal page created by Ziyan Zhai and Zhuoyu Li

### PR DESCRIPTION
**Pull request by ZhuoYuLi4396**
The header of this page can't refer to the default header. Ziyan zhai added a menu to the default header (high fidelity requires it).

### CODE REVIEW

**Comment by ZhuoYuLi4396** [comment]
Screenshots of the page are provided in the Trello

**Comment by mukundnivas** [comment]
Currently reviewing the code. I'm running into issues with testing this PR branch out, I'll get to it tomorrow and merge if everything seems alright. I also might have to get you to restructure images/assets folder location. Good work so far!

**Comment by ZhuoYuLi4396** [comment]
f56480df7d5f183d018571df3d25d71

**Comment by ZhuoYuLi4396** [comment]
0e667667972ecaaaa953aadc6fe14b9
2e43c0f9ee129bf3c9c26b9a3a22f87

**Comment by ZhuoYuLi4396** [comment]
bf0fefed506c540b9c6445327318eab
58c36fbf23f3de4854598f61ca409b3

**Review by Aaron-Vandersluys-Code — APPROVED** [review]
Well done, everything looks good on my end.

**Pull request merged**
