### PR TITLE
Project page

### PR DESCRIPTION
**Pull request by Bhavikasood88**
Updated code files

### CODE REVIEW

**Review by Davinder-2001 — APPROVED** [review]
Great Work bhavika.
The request is ready to merge.

**Comment by jsuwannakoot** [comment]
Can you please post the screenshot of your code running here for a final check before merging?

**Comment by Bhavikasood88** [comment]
Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Review by Aaron-Vandersluys-Code — APPROVED** [review]
Hi Bhavika, I can see you have made some great progress on the Project page. Well done. These additions will be merged into the main repo.

**Pull request merged**
