### PR TITLE
Reset password page front end work including bootstrap framework

### PR DESCRIPTION
**Pull request by muhammadrehanqureshi**

### CODE REVIEW

**Comment by Davinder-2001** [comment]
Hi Muhammad, Great Work. Would you also be able to include a screenshot in the description of the final code running?

**Comment by muhammadrehanqureshi** [comment]
IMG-20230922-WA0000

**Comment by muhammadrehanqureshi** [comment]
> Hi Muhammad, Great Work. Would you also be able to include a screenshot in the description of the final code running?

IMG-20230922-WA0000

**Review by MatheeshaNPalliyaguruge — APPROVED** [review]
Went through the code and reviewed it. No changes needed from my side for code best practices.

**Review by Aaron-Vandersluys-Code — APPROVED** [review]
Hi Muhammed. Great work on providing well written code. Everything here is done quite well. Unfortunately the Chameleon Website is a React Native application, and this particular implementation will not run with all the other components, as the Chameleon website does not utilise standard HTML. 

With that said, it is my understanding that you will be returning in trimester 3 and will have the opportunity to make updates. This code will be merged with the main repo to ensure it can be maintained until the next trimester. What you will be required to do at that time is to port the existing code to React Native and jsx. Fortunately most of what you have written here will be reusable. 

In the meantime, you can review the following sources of information to help you gain an understanding of React Native and jsx: 

https://reactnative.dev/docs/getting-started
https://www.w3schools.com/react/react_jsx.asp
https://www.w3schools.com/react/react_components.asp

**Comment by mukundnivas** [comment]
@Aaron-Vandersluys-Code could you please clean this PR from the Repo. When you're done porting the "password reset page" vanilla JS to React JSX. 

Thanks!
[Trello Card](https://trello.com/c/2X7vSOZY)

**Pull request merged**
